era: Run3_2025
luminosity: 110730.86  # pb-1, https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis#DATA_AN2 brilcalc lumi -b "STABLE BEAMS"  -i Cert_Collisions2025_391658_398903_Golden.json (no normtag available)
nano_version: v15
datasets_link_to_era: Run3_2024
crossSectionsFile: FLAF/config/crossSections13p6TeV.yaml
MET_flags: # https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#Run_3_2024_data_and_MC_Recommend
  - Flag_goodVertices
  - Flag_globalSuperTightHalo2016Filter
  - Flag_EcalDeadCellTriggerPrimitiveFilter
  - Flag_BadPFMuonFilter
  - Flag_BadPFMuonDzFilter
  - Flag_hfNoisyHitsFilter
  - Flag_eeBadScFilter
  - Flag_ecalBadCalibFilter
lumiFile: Corrections/data/golden_json/Cert_Collisions2025_391658_398903_Golden.json
